import { Router } from 'express';
import { createOrder, getOrderById, getMyOrders, downloadInvoice } from '../controllers/order.controller.js';
import { authenticateUser } from '../middleware/auth.js';

const router = Router();

// POST /api/orders/create - Initialize order and get Razorpay order ID
router.post('/create', createOrder);

// GET /api/orders/my-orders - Get logged-in user order history
router.get('/my-orders', authenticateUser, getMyOrders);

// GET /api/orders/invoice/:orderId - Download PDF invoice generated by Worker 2
router.get('/invoice/:orderId', downloadInvoice);

// GET /api/orders/:id - Get single order details and activity logs
router.get('/:id', getOrderById);

export default router;
